version: "3.9"

services:
  web:
    image: ${DOCKERHUB_USERNAME}/login-whitelabel:${APP_VERSION}
    container_name: login-whitelabel
    ports:
      - "3057:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
